### ISSUE TITLE
PyPy compilation fails with error: too many initializers

### ISSUE THREAD

**Issue by BastianZim** [dwavesystems/dwave-greedy#29]
This is the same as https://github.com/dwavesystems/dimod/issues/1169

Posting this more as an FYI than a request for help as it's not super high priority.

Logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=504553&view=logs&jobId=517fe804-fa30-5dc2-1413-330699242c05&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412

**Comment by randomir** [comment]
We don't support pypy.
