### ISSUE TITLE
greedy as a sampleset post-processing tool

### ISSUE THREAD

**Issue by pau557** [dwavesystems/dwave-greedy#4]
I'm using `greedy` to post-process a `sampleset`. It would be great if when a sampleset is passed as `initial_states`, a copy of that same sampleset with greedy post-processing is returned. 
The current behaviour makes a new sampleset, which doesn't keep the rest of metadata.
https://github.com/dwavesystems/dwave-greedy/blob/75d5dcd4ce6ca7b3a2f83d41f50ce613f24c0b0a/greedy/sampler.py#L221

Desired use:
```
result = DWaveSampler().sample(bqm)
greedy_pp = greedy.SteepestDescentSolver().post_process(bqm, sampleset=result)
```

**Comment by randomir** [comment]
Closing as won't do. Seems too specific for a particular use case, and it's trivially implemented with [the above utility function](https://github.com/dwavesystems/dwave-greedy/issues/4#issuecomment-622667769).
